/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 4

enum ts_symbol_identifiers {
  anon_sym_func = 1,
  anon_sym_AT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_COLON = 6,
  sym_struct_definition = 7,
  sym_interface_definition = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_async = 11,
  anon_sym_LPAREN_RPAREN = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_SEMI = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  aux_sym_identifier_token1 = 18,
  aux_sym_identifier_token2 = 19,
  anon_sym_DQUOTE = 20,
  aux_sym_string_literal_token1 = 21,
  anon_sym_BSLASH = 22,
  anon_sym_n = 23,
  anon_sym_r = 24,
  anon_sym_t = 25,
  anon_sym_true = 26,
  anon_sym_false = 27,
  aux_sym_float_literal_token1 = 28,
  aux_sym_float_literal_token2 = 29,
  aux_sym_float_literal_token3 = 30,
  sym_integer_literal = 31,
  sym_source_file = 32,
  sym_definition = 33,
  sym_function_definition = 34,
  sym_function_signature = 35,
  sym_parameter_list = 36,
  sym_function_param = 37,
  sym__role_type = 38,
  sym_role_type_shared = 39,
  sym_role_type_normal = 40,
  sym_value_type = 41,
  sym_async_type = 42,
  sym_list_type = 43,
  sym_closure_type = 44,
  sym_named_type = 45,
  sym__role_ident = 46,
  sym_block = 47,
  sym_statement = 48,
  sym_stmt_expression = 49,
  sym_stmt_variable_decl = 50,
  sym_expression = 51,
  sym_identifier = 52,
  sym__literal = 53,
  sym_string_literal = 54,
  sym_boolean_literal = 55,
  sym_float_literal = 56,
  aux_sym_parameter_list_repeat1 = 57,
  aux_sym_role_type_shared_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
  aux_sym_string_literal_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_func] = "func",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [sym_struct_definition] = "struct_definition",
  [sym_interface_definition] = "interface_definition",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_async] = "async",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [aux_sym_identifier_token1] = "identifier_token1",
  [aux_sym_identifier_token2] = "identifier_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_n] = "n",
  [anon_sym_r] = "r",
  [anon_sym_t] = "t",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [aux_sym_float_literal_token1] = "float_literal_token1",
  [aux_sym_float_literal_token2] = "float_literal_token2",
  [aux_sym_float_literal_token3] = "float_literal_token3",
  [sym_integer_literal] = "integer_literal",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_function_definition] = "function_definition",
  [sym_function_signature] = "function_signature",
  [sym_parameter_list] = "parameter_list",
  [sym_function_param] = "function_param",
  [sym__role_type] = "_role_type",
  [sym_role_type_shared] = "role_type_shared",
  [sym_role_type_normal] = "role_type_normal",
  [sym_value_type] = "value_type",
  [sym_async_type] = "async_type",
  [sym_list_type] = "list_type",
  [sym_closure_type] = "closure_type",
  [sym_named_type] = "named_type",
  [sym__role_ident] = "_role_ident",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_stmt_expression] = "stmt_expression",
  [sym_stmt_variable_decl] = "stmt_variable_decl",
  [sym_expression] = "expression",
  [sym_identifier] = "identifier",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_float_literal] = "float_literal",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_role_type_shared_repeat1] = "role_type_shared_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_struct_definition] = sym_struct_definition,
  [sym_interface_definition] = sym_interface_definition,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_async] = anon_sym_async,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [aux_sym_identifier_token2] = aux_sym_identifier_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [aux_sym_float_literal_token1] = aux_sym_float_literal_token1,
  [aux_sym_float_literal_token2] = aux_sym_float_literal_token2,
  [aux_sym_float_literal_token3] = aux_sym_float_literal_token3,
  [sym_integer_literal] = sym_integer_literal,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_function_definition] = sym_function_definition,
  [sym_function_signature] = sym_function_signature,
  [sym_parameter_list] = sym_parameter_list,
  [sym_function_param] = sym_function_param,
  [sym__role_type] = sym__role_type,
  [sym_role_type_shared] = sym_role_type_shared,
  [sym_role_type_normal] = sym_role_type_normal,
  [sym_value_type] = sym_value_type,
  [sym_async_type] = sym_async_type,
  [sym_list_type] = sym_list_type,
  [sym_closure_type] = sym_closure_type,
  [sym_named_type] = sym_named_type,
  [sym__role_ident] = sym__role_ident,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_stmt_expression] = sym_stmt_expression,
  [sym_stmt_variable_decl] = sym_stmt_variable_decl,
  [sym_expression] = sym_expression,
  [sym_identifier] = sym_identifier,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_float_literal] = sym_float_literal,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_role_type_shared_repeat1] = aux_sym_role_type_shared_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_interface_definition] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_async] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_float_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_literal_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_param] = {
    .visible = true,
    .named = true,
  },
  [sym__role_type] = {
    .visible = false,
    .named = true,
  },
  [sym_role_type_shared] = {
    .visible = true,
    .named = true,
  },
  [sym_role_type_normal] = {
    .visible = true,
    .named = true,
  },
  [sym_value_type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_async_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_closure_type] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym__role_ident] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_stmt_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt_variable_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_role_type_shared_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_parameters = 3,
  field_return_type = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 1},
  [7] = {.index = 12, .length = 2},
  [8] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 1},
    {field_parameters, 2},
  [3] =
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 3},
  [6] =
    {field_name, 3},
    {field_parameters, 4},
  [8] =
    {field_name, 3},
    {field_parameters, 4},
    {field_return_type, 5},
  [11] =
    {field_name, 0},
  [12] =
    {field_name, 1},
    {field_value, 3},
  [14] =
    {field_name, 1},
    {field_value, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 14,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_definition,
  sym_expression,
  sym_statement,
  sym_value_type,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_definition] = {.index = 0, .length = 3},
  [sym_expression] = {.index = 3, .length = 5},
  [sym_statement] = {.index = 8, .length = 2},
  [sym_value_type] = {.index = 10, .length = 4},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_function_definition,
    sym_interface_definition,
    sym_struct_definition,
  [3] =
    sym_boolean_literal,
    sym_float_literal,
    sym_identifier,
    sym_integer_literal,
    sym_string_literal,
  [8] =
    sym_stmt_expression,
    sym_stmt_variable_decl,
  [10] =
    sym_async_type,
    sym_closure_type,
    sym_list_type,
    sym_named_type,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '"', 74,
        '(', 39,
        ')', 41,
        ',', 40,
        '.', 33,
        ':', 42,
        ';', 52,
        '=', 55,
        '@', 38,
        '[', 45,
        '\\', 77,
        ']', 46,
        '_', 34,
        'a', 25,
        'f', 8,
        'i', 21,
        'l', 17,
        'n', 78,
        'r', 79,
        's', 27,
        't', 80,
        '{', 50,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 74,
        '(', 7,
        '.', 33,
        '_', 34,
        'f', 57,
        'l', 60,
        't', 66,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(57);
      if (lookahead == 't') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead == '\\') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '(', 39,
        ')', 41,
        ',', 40,
        ':', 42,
        ';', 52,
        '=', 55,
        '@', 38,
        '[', 45,
        ']', 46,
        '_', 34,
        '{', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '=') ADVANCE(55);
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == '{') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        ')', 41,
        ',', 40,
        '=', 55,
        '[', 45,
        ']', 46,
        '_', 34,
        'a', 67,
        'f', 70,
        '{', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 7:
      if (lookahead == ')') ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 32:
      if (lookahead == 'y') ADVANCE(22);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_struct_definition);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_interface_definition);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_async);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_async);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'a') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'c') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'c') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'e') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'l') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'n') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'r') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 's') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 's') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'u') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'u') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (lookahead == 'y') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_identifier_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_float_literal_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_float_literal_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_float_literal_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_struct_definition] = ACTIONS(1),
    [sym_interface_definition] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_async] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [aux_sym_float_literal_token1] = ACTIONS(1),
    [aux_sym_float_literal_token2] = ACTIONS(1),
    [aux_sym_float_literal_token3] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym_definition] = STATE(69),
    [sym_function_definition] = STATE(72),
    [sym_function_signature] = STATE(61),
    [anon_sym_func] = ACTIONS(3),
    [sym_struct_definition] = ACTIONS(5),
    [sym_interface_definition] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(12), 1,
      aux_sym_identifier_token1,
    ACTIONS(15), 1,
      aux_sym_identifier_token2,
    ACTIONS(18), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      aux_sym_float_literal_token3,
    ACTIONS(30), 1,
      sym_integer_literal,
    STATE(67), 1,
      sym_expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(24), 2,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 2,
      sym_stmt_expression,
      sym_stmt_variable_decl,
    STATE(74), 5,
      sym_identifier,
      sym__literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_float_literal,
  [48] = 13,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      anon_sym_let,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      aux_sym_float_literal_token3,
    ACTIONS(49), 1,
      sym_integer_literal,
    STATE(67), 1,
      sym_expression,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    STATE(4), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 2,
      sym_stmt_expression,
      sym_stmt_variable_decl,
    STATE(74), 5,
      sym_identifier,
      sym__literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_float_literal,
  [96] = 13,
    ACTIONS(35), 1,
      anon_sym_let,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      aux_sym_float_literal_token3,
    ACTIONS(49), 1,
      sym_integer_literal,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_expression,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 2,
      sym_stmt_expression,
      sym_stmt_variable_decl,
    STATE(74), 5,
      sym_identifier,
      sym__literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_float_literal,
  [144] = 10,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(38), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
    ACTIONS(55), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [182] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      aux_sym_float_literal_token3,
    ACTIONS(49), 1,
      sym_integer_literal,
    STATE(84), 1,
      sym_expression,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    STATE(74), 5,
      sym_identifier,
      sym__literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_float_literal,
  [216] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      aux_sym_float_literal_token3,
    ACTIONS(49), 1,
      sym_integer_literal,
    STATE(79), 1,
      sym_expression,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    STATE(74), 5,
      sym_identifier,
      sym__literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_float_literal,
  [250] = 10,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(68), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [284] = 10,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(70), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [318] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(34), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [349] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(83), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [380] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(78), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [411] = 9,
    ACTIONS(37), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      aux_sym_identifier_token2,
    ACTIONS(53), 1,
      anon_sym_func,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_async,
    STATE(27), 1,
      sym_identifier,
    STATE(33), 1,
      sym__role_ident,
    STATE(63), 1,
      sym_value_type,
    STATE(37), 4,
      sym_async_type,
      sym_list_type,
      sym_closure_type,
      sym_named_type,
  [442] = 1,
    ACTIONS(65), 11,
      anon_sym_AT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [456] = 2,
    ACTIONS(67), 5,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    ACTIONS(69), 6,
      anon_sym_let,
      aux_sym_identifier_token2,
      anon_sym_true,
      anon_sym_false,
      aux_sym_float_literal_token3,
      sym_integer_literal,
  [472] = 2,
    ACTIONS(71), 5,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    ACTIONS(73), 6,
      anon_sym_let,
      aux_sym_identifier_token2,
      anon_sym_true,
      anon_sym_false,
      aux_sym_float_literal_token3,
      sym_integer_literal,
  [488] = 2,
    ACTIONS(75), 5,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    ACTIONS(77), 6,
      anon_sym_let,
      aux_sym_identifier_token2,
      anon_sym_true,
      anon_sym_false,
      aux_sym_float_literal_token3,
      sym_integer_literal,
  [504] = 2,
    ACTIONS(79), 5,
      anon_sym_RBRACE,
      aux_sym_identifier_token1,
      anon_sym_DQUOTE,
      aux_sym_float_literal_token1,
      aux_sym_float_literal_token2,
    ACTIONS(81), 6,
      anon_sym_let,
      aux_sym_identifier_token2,
      anon_sym_true,
      anon_sym_false,
      aux_sym_float_literal_token3,
      sym_integer_literal,
  [520] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(56), 3,
      sym__role_type,
      sym_role_type_shared,
      sym_role_type_normal,
  [539] = 1,
    ACTIONS(87), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [550] = 1,
    ACTIONS(89), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [561] = 1,
    ACTIONS(91), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [572] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_identifier,
    ACTIONS(93), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(75), 3,
      sym__role_type,
      sym_role_type_shared,
      sym_role_type_normal,
  [591] = 1,
    ACTIONS(95), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [602] = 5,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
    STATE(35), 3,
      sym__role_type,
      sym_role_type_shared,
      sym_role_type_normal,
  [621] = 1,
    ACTIONS(97), 8,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACE,
      anon_sym_EQ,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [632] = 2,
    ACTIONS(99), 1,
      anon_sym_AT,
    ACTIONS(101), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [643] = 2,
    ACTIONS(103), 3,
      anon_sym_func,
      anon_sym_async,
      aux_sym_identifier_token2,
    ACTIONS(105), 3,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_identifier_token1,
  [654] = 2,
    ACTIONS(107), 3,
      anon_sym_func,
      anon_sym_async,
      aux_sym_identifier_token2,
    ACTIONS(109), 3,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_identifier_token1,
  [665] = 2,
    ACTIONS(111), 3,
      anon_sym_func,
      anon_sym_async,
      aux_sym_identifier_token2,
    ACTIONS(113), 3,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_identifier_token1,
  [676] = 1,
    ACTIONS(115), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [684] = 1,
    ACTIONS(117), 5,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_n,
      anon_sym_r,
      anon_sym_t,
  [692] = 1,
    ACTIONS(119), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [700] = 1,
    ACTIONS(121), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [708] = 1,
    ACTIONS(123), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [716] = 4,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_function_param,
    STATE(71), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [730] = 1,
    ACTIONS(127), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [738] = 1,
    ACTIONS(129), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_EQ,
  [746] = 4,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(133), 1,
      aux_sym_string_literal_token1,
    ACTIONS(136), 1,
      anon_sym_BSLASH,
    STATE(39), 1,
      aux_sym_string_literal_repeat1,
  [759] = 3,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_role_type_shared_repeat1,
    ACTIONS(142), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [770] = 3,
    STATE(62), 1,
      sym_function_param,
    STATE(71), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [781] = 4,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      aux_sym_string_literal_token1,
    ACTIONS(148), 1,
      anon_sym_BSLASH,
    STATE(44), 1,
      aux_sym_string_literal_repeat1,
  [794] = 3,
    ACTIONS(150), 1,
      anon_sym_AT,
    STATE(60), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [805] = 4,
    ACTIONS(148), 1,
      anon_sym_BSLASH,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      aux_sym_string_literal_token1,
    STATE(39), 1,
      aux_sym_string_literal_repeat1,
  [818] = 2,
    STATE(55), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [826] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_role_type_shared_repeat1,
  [836] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_role_type_shared_repeat1,
  [846] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(162), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_role_type_shared_repeat1,
  [856] = 3,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_parameter_list_repeat1,
  [866] = 3,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_parameter_list_repeat1,
  [876] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      aux_sym_role_type_shared_repeat1,
  [886] = 2,
    STATE(46), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [894] = 2,
    ACTIONS(172), 1,
      aux_sym_string_literal_token1,
    ACTIONS(131), 2,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
  [902] = 2,
    STATE(51), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [910] = 1,
    ACTIONS(142), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [916] = 2,
    STATE(59), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [924] = 3,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_parameter_list_repeat1,
  [934] = 2,
    STATE(64), 1,
      sym_identifier,
    ACTIONS(37), 2,
      aux_sym_identifier_token1,
      aux_sym_identifier_token2,
  [942] = 2,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_parameter_list,
  [949] = 2,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_parameter_list,
  [956] = 2,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    STATE(82), 1,
      sym_block,
  [963] = 1,
    ACTIONS(177), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [968] = 1,
    ACTIONS(183), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [973] = 2,
    ACTIONS(185), 1,
      anon_sym_COLON,
    ACTIONS(187), 1,
      anon_sym_EQ,
  [980] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
  [984] = 1,
    ACTIONS(191), 1,
      anon_sym_SEMI,
  [988] = 1,
    ACTIONS(193), 1,
      anon_sym_SEMI,
  [992] = 1,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
  [996] = 1,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [1000] = 1,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
  [1004] = 1,
    ACTIONS(201), 1,
      anon_sym_COLON,
  [1008] = 1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
  [1012] = 1,
    ACTIONS(205), 1,
      anon_sym_AT,
  [1016] = 1,
    ACTIONS(207), 1,
      anon_sym_SEMI,
  [1020] = 1,
    ACTIONS(209), 1,
      anon_sym_LPAREN_RPAREN,
  [1024] = 1,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
  [1028] = 1,
    ACTIONS(213), 1,
      anon_sym_SEMI,
  [1032] = 1,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [1036] = 1,
    ACTIONS(217), 1,
      anon_sym_SEMI,
  [1040] = 1,
    ACTIONS(219), 1,
      anon_sym_SEMI,
  [1044] = 1,
    ACTIONS(221), 1,
      anon_sym_SEMI,
  [1048] = 1,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [1052] = 1,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
  [1056] = 1,
    ACTIONS(227), 1,
      anon_sym_SEMI,
  [1060] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [1064] = 1,
    ACTIONS(65), 1,
      anon_sym_LPAREN_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 182,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 250,
  [SMALL_STATE(9)] = 284,
  [SMALL_STATE(10)] = 318,
  [SMALL_STATE(11)] = 349,
  [SMALL_STATE(12)] = 380,
  [SMALL_STATE(13)] = 411,
  [SMALL_STATE(14)] = 442,
  [SMALL_STATE(15)] = 456,
  [SMALL_STATE(16)] = 472,
  [SMALL_STATE(17)] = 488,
  [SMALL_STATE(18)] = 504,
  [SMALL_STATE(19)] = 520,
  [SMALL_STATE(20)] = 539,
  [SMALL_STATE(21)] = 550,
  [SMALL_STATE(22)] = 561,
  [SMALL_STATE(23)] = 572,
  [SMALL_STATE(24)] = 591,
  [SMALL_STATE(25)] = 602,
  [SMALL_STATE(26)] = 621,
  [SMALL_STATE(27)] = 632,
  [SMALL_STATE(28)] = 643,
  [SMALL_STATE(29)] = 654,
  [SMALL_STATE(30)] = 665,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 684,
  [SMALL_STATE(33)] = 692,
  [SMALL_STATE(34)] = 700,
  [SMALL_STATE(35)] = 708,
  [SMALL_STATE(36)] = 716,
  [SMALL_STATE(37)] = 730,
  [SMALL_STATE(38)] = 738,
  [SMALL_STATE(39)] = 746,
  [SMALL_STATE(40)] = 759,
  [SMALL_STATE(41)] = 770,
  [SMALL_STATE(42)] = 781,
  [SMALL_STATE(43)] = 794,
  [SMALL_STATE(44)] = 805,
  [SMALL_STATE(45)] = 818,
  [SMALL_STATE(46)] = 826,
  [SMALL_STATE(47)] = 836,
  [SMALL_STATE(48)] = 846,
  [SMALL_STATE(49)] = 856,
  [SMALL_STATE(50)] = 866,
  [SMALL_STATE(51)] = 876,
  [SMALL_STATE(52)] = 886,
  [SMALL_STATE(53)] = 894,
  [SMALL_STATE(54)] = 902,
  [SMALL_STATE(55)] = 910,
  [SMALL_STATE(56)] = 916,
  [SMALL_STATE(57)] = 924,
  [SMALL_STATE(58)] = 934,
  [SMALL_STATE(59)] = 942,
  [SMALL_STATE(60)] = 949,
  [SMALL_STATE(61)] = 956,
  [SMALL_STATE(62)] = 963,
  [SMALL_STATE(63)] = 968,
  [SMALL_STATE(64)] = 973,
  [SMALL_STATE(65)] = 980,
  [SMALL_STATE(66)] = 984,
  [SMALL_STATE(67)] = 988,
  [SMALL_STATE(68)] = 992,
  [SMALL_STATE(69)] = 996,
  [SMALL_STATE(70)] = 1000,
  [SMALL_STATE(71)] = 1004,
  [SMALL_STATE(72)] = 1008,
  [SMALL_STATE(73)] = 1012,
  [SMALL_STATE(74)] = 1016,
  [SMALL_STATE(75)] = 1020,
  [SMALL_STATE(76)] = 1024,
  [SMALL_STATE(77)] = 1028,
  [SMALL_STATE(78)] = 1032,
  [SMALL_STATE(79)] = 1036,
  [SMALL_STATE(80)] = 1040,
  [SMALL_STATE(81)] = 1044,
  [SMALL_STATE(82)] = 1048,
  [SMALL_STATE(83)] = 1052,
  [SMALL_STATE(84)] = 1056,
  [SMALL_STATE(85)] = 1060,
  [SMALL_STATE(86)] = 1064,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [12] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closure_type, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 3, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 5, 0, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_expression, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt_expression, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_variable_decl, 5, 0, 7),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt_variable_decl, 5, 0, 7),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_variable_decl, 7, 0, 8),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt_variable_decl, 7, 0, 8),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_type_normal, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_type_normal, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_type_shared, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_type_normal, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_role_type_shared, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__role_ident, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_async_type, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__role_ident, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_type, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closure_type, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_role_type_shared_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_role_type_shared_repeat1, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_param, 3, 0, 6),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 4, 0, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_signature, 6, 0, 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [211] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tempo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tempo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
